stages:
  - test
  - build
  - deploy

.rails_template: &rails_template
  image: ruby:2.6.5

  services:
    - postgres:latest

  variables:
    POSTGRES_DB: gitlab_ci_test
    POSTGRES_USER: runner
    POSTGRES_HOST_AUTH_METHOD: trust

  stage: test

  cache:
    paths:
      - vendor/bundle

  before_script:
    - apt-get update -q
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs yarn
    - gem install bundler --no-document
    - bundle check --path vendor/bundle || bundle install --path vendor/bundle
    - yarn install
    - cp -f config/database.yml{.gitlab,}

rails_test:
  <<: *rails_template

  script:
    - bundle exec rake

rails_style:
  <<: *rails_template

  script:
    - bundle exec rake check_style

bundle_audit:
  <<: *rails_template
  script:
    - bundle exec bundle audit update
    - bundle exec bundle audit --ignore CVE-2020-5247 CVE-2020-8185 CVE-2020-8166 CVE-2020-8164 CVE-2020-5267 CVE-2020-8167 CVE-2020-8162 CVE-2020-8165 CVE-2020-5257 CVE-2020-11082 CVE-2020-5249 CVE-2020-11076 CVE-2020-11077 CVE-2020-5247 CVE-2020-8184 CVE-2020-7663
