version: '3'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ${PWD}/deco.json.template:/run/secrets/deco.json

  database:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: