version: '3.3'

services:

  web:
    build: .
    ports:
      - "3000:3000"

    volumes:
      - .:/usr/src/app
      - ./deco.json.template:/run/secrets/deco.json

  database:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
