version: '3'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  database:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  db_data: