default: &default
  adapter: mysql2
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('MYSQL_USER') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
  encoding: utf8
  reconnect: false
  pool: 5

development:
  <<: *default
  database: cardswipr_development

test:
  <<: *default
  database: cardswipr_test

production:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE') %>
