development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yale_api_portal: <%= ENV["YALE_API_PORTAL_ID_LOOKUP"] %>
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yale_api_portal: <%= ENV["YALE_API_PORTAL_ID_LOOKUP"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yale_api_portal: <%= ENV["YALE_API_PORTAL_ID_LOOKUP"] %>