default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  id_api_url:      <%= ENV["ID_API_URL"] %>
  id_api_username: <%= ENV["ID_API_USERNAME"] %>
  id_api_password: <%= ENV["ID_API_PASSWORD"] %>

production:
  <<: *default

development:
  <<: *default

local:
  <<: *default

test:
  <<: *default
