default: &default
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  id_api_url:      <%= ENV.fetch("ID_API_URL") %>
  id_api_username: <%= ENV.fetch("ID_API_USERNAME") %>
  id_api_password: <%= ENV.fetch("ID_API_PASSWORD") %>

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
