default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yale_api_portal: <%= ENV["YALE_API_PORTAL_ID_LOOKUP"] %>
  id_api_username: <%= ENV["ID_API_USERNAME"] %>
  id_api_password: <%= ENV["ID_API_PASSWORD"] %>
  ssl_client_certificate: <%= ENV["CARDSWIPR_CLIENT_CERT"] %>
  ssl_client_key: <%= ENV["CARDSWIPR_CLIENT_KEY"] %>

production:
  <<: *default

development:
  <<: *default

local:
  <<: *default

test:
  <<: *default
